- name: Restart host
  ansible.builtin.reboot:
  listen: 'Reboot and wait'
  become: true

- name: Wait for server to restart
  ansible.builtin.wait_for:
    host: '{{ (ansible_ssh_host | default(ansible_host)) | default(inventory_hostname) }}'
    delay: 10
  connection: local
  become: false
  listen: 'Reboot and wait'

- name: Update GRUB
  ansible.builtin.command: update-grub
  become: true
  register: grub_update
  changed_when: grub_update.rc != 0
