---
- name: Proxmox basic setup after upgrade
  tags: pve-upgrade
  become: true
  block:
    - name: Disable enterprise repo
      ansible.builtin.apt_repository:
        repo: 'deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }}  pve-enterprise'
        state: absent

    - name: Add PVE repo no-subscription
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64] http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription'
        filename: pve-install-repo
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        upgrade: full
        cache_valid_time: 86400

    - name: Upgrade the OS
      ansible.builtin.apt:
        upgrade: dist

    - name: Disable subscription notice
      ansible.builtin.replace:
        path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
        regexp: '^(.*)Ext\.Msg\.show\(\{(.*)$\n^(.*)No valid subscription(.*)$'
        replace: '\1void({\2\n\3No valid subscription\4'
    # make sure to clean up browser cache
