- name: Install PVE
  tags: pve-install
  block:
    - name: Add PVE GPG keys
      ansible.builtin.apt_key:
        url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
        keyring: /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
        state: present

    - name: Add PVE repo no-subscription
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64] http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription'
        filename: pve-install-repo
        state: present

    - name: Disable enterprise repo
      ansible.builtin.apt_repository:
        repo: 'deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }}  pve-enterprise'
        state: absent

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        upgrade: full

    - name: Install Proxmox kernel
      ansible.builtin.apt:
        name: proxmox-default-kernel

    - name: Install Proxmox packages
      ansible.builtin.apt:
        name: '{{ item }}'
      with_items:
        - proxmox-ve
        - postfix
        - open-iscsi
        - chrony

    - name: Disable enterprise repo
      ansible.builtin.apt_repository:
        repo: 'deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }}  pve-enterprise'
        state: absent

    - name: Enable PCI Passthrough
      ansible.builtin.include_tasks: pci-passthrough.yml

    - name: Do cleanup
      ansible.builtin.include_tasks: cleanup.yml
